project:
  type: book
  output-dir: docs

book:
  title: "R data science"
  reader-mode: true
  chapters:
    - index.qmd
    - part: "Programming"
      chapters: 
        - basic_data_type_class.qmd
        - control_structure.qmd
        - function.qmd
        - efficient.qmd
        - functional_programming.qmd    
    
    - part: "Data science"
      chapters: 
        - I-O.qmd
        - useful_function.qmd
        - base_graphics.qmd
        - ggplot2_graphics.qmd
        - ggplot2_extensions.qmd




execute:
  cache: true
  message: false #阻止消息或警告出现在完成的文件中
  warning: false
# eval: false阻止对代码进行评估。（显然，如果不运行代码，则不会生成任何结果）
# include: false运行代码，但不会在最终文档中显示代码或结果。
# echo: false阻止代码，但不会阻止结果出现在完成的文件中
toc: true
toc-depth: 4
number-sections: true
number-depth: 4

code-fold: true
code-tools: true
code-link: true

knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
    
format: 
  html: 
    theme: cosmo
    df-print: kable

    html-math-method: katex
    callout-appearance: simple
editor: visual



