project:
  type: book
  output-dir: docs

book:
  title: "RDataScience_notes"
  reader-mode: true

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd





format:
  html:
    theme: cosmo


editor: visual

